name: "Svelte Check PR Annotator"
description: "Annotate pull requests with Svelte-Check errors detected during CI"
author: "prgm.dev"
runs:
  using: "composite"
  steps:
    - run: echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"
      shell: bash
